use Sinefil

insert into [User] (Username,Email,[Password],[Role]) values ('Tugce','tugcenurmatur@gmail.com','123456','Admin')


insert into Film (Title,Director,[Year],Genre,[Description],ImgUrl) values ('Parasite','Bong Joon Ho',2019,'Dark Comedy, Tragedy', 'Reviewers say Parasite is a complex film exploring class disparity and social inequality, praised for its unique storytelling and sharp writing. Critics commend director Bong Joon-ho and the strong cast performances. The film blends comedy, drama, thriller, and horror elements effectively. However, some reviewers find it overhyped, questioning its originality and execution. Despite mixed opinions, many agree that Parasite provokes thought and discussion about societal issues.','https://manifold.press/images/content/manifold-sas-17-parazit-bong-joon-ho-afis.jpg')
insert into Film (Title,Director,[Year],Genre,[Description],ImgUrl) values ('The Shawshank Redemption','Frank Darabont',1994,'Drama', 'A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and trying to remain hopeful through simple compassion..','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEVyi0hqPG5gllmnJtdHu9dFw9nAYX7hYFFQ&s')
insert into Film (Title,Director,[Year],Genre,[Description],ImgUrl) values ('Memento','Christopher Nolan',2000,'Mystery,Thriller', 'A former insurance investigator who now suffers from anterograde amnesia uses notes and tattoos to hunt down his wife`s murderer.','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkreNY0wTrnjeqE-RJrQWjAbFYtXK6H72s8A&s')
insert into Film (Title,Director,[Year],Genre,[Description],ImgUrl) values ('The Prestige','Christopher Nolan','2006','Drama, Mystery, Sci-Fi, Thriller', 'Rival 19th-century magicians engage in a bitter battle for trade secrets.','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9r8jQ6DMr1evRVg5M2Gpx4Mx4Guxl4kcCfg&s')
insert into Film (Title,Director,[Year],Genre,[Description],ImgUrl) values (' American History X','Tony Kaye','1998','Crime,Drama', 'Living a life marked by violence, neo-Nazi Derek finally goes to prison after killing two black youths. Upon his release, Derek vows to change; he hopes to prevent his brother, Danny, who idolizes Derek, from following in his footsteps.','https://upload.wikimedia.org/wikipedia/en/3/39/American_History_X_poster.png')
